python2 engine.py "select * from table1"
python2 engine.py "select * from table2"
python2 engine.py "select A from table1,table2 where table1.B=table2.B"
python2 engine.py "select Distinct A from table1"
python2 engine.py "select * from table1,table2"
python2 engine.py "select max(A) from table1"
python2 engine.py "Select table1.A,table2.D from table1,table2 where table1.A=922 AND table2.B = 731;"
#echo "Syntax error expected"
python2 engine.py "Select * from;"
python2 engine.py "Select sum(A) from table1"
#echo "Syntax error expected B is ambigious i.e syntax error result null" 
python2 engine.py "Select A,B from table1,table2 where table1.B=table2.B"
python2 engine.py "Select A,table1.B from table1,table2 where table1.B=table2.B"
python2 engine.py "Select A from table1 where table1.A >= 500"
python2 engine.py "Select A from table1 where table1.A <= 500"
#echo "Syntax Error Expected"
python2 engine.py "Select A from table1 where table1.A => 500"
python2 engine.py "Select A from table1 where table1.A = 500"
#echo "Case of syntax error of operand"
python2 engine.py "Select A from table1 where table1.A & 500"
#echo "Ambigious column error"
python2 engine.py "Select B from table1,table2"
#echo "for such query we need natural join"
python2 engine.py "select * from table1,table2 where table1.B=table2.B and table2.D=11191"